# Generated by Django 6.0.3 on 2026-03-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMRADEAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
